// <auto-generated />
using System;
using BlueBird.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueBird.Migrations
{
    [DbContext(typeof(UserFormContext))]
    partial class UserFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlueBird.Models.Sector", b =>
                {
                    b.Property<Guid>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserFormFillingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("SectorId");

                    b.HasIndex("UserFormFillingId");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("BlueBird.Models.SectorData", b =>
                {
                    b.Property<Guid>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("SectorId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("SectorData");

                    b.HasData(
                        new
                        {
                            SectorId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Name = "Manufacturing",
                            Value = 1
                        },
                        new
                        {
                            SectorId = new Guid("41ee21cf-1645-407f-8f41-6446b04b1080"),
                            Name = "Construction materials",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 19
                        },
                        new
                        {
                            SectorId = new Guid("dbf82b38-0b27-4dac-b932-36a7dae1dc96"),
                            Name = "Electronics and Optics",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 18
                        },
                        new
                        {
                            SectorId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Name = "Food and Beverage",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 6
                        },
                        new
                        {
                            SectorId = new Guid("ed43d82e-6651-4015-88b1-f6b081704da4"),
                            Name = "Bakery & confectionery products",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 342
                        },
                        new
                        {
                            SectorId = new Guid("9b22497e-b227-41c7-97c2-1790c1df2708"),
                            Name = "Beverages",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 43
                        },
                        new
                        {
                            SectorId = new Guid("a12a0ba9-599a-4fa7-9712-c90737e83c7c"),
                            Name = "Fish & fish products",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 42
                        },
                        new
                        {
                            SectorId = new Guid("8329d8e0-43b2-4e91-b1da-1493ba53ff56"),
                            Name = "Meat & meat products",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 40
                        },
                        new
                        {
                            SectorId = new Guid("b76b3ed6-dfa5-4ac0-8515-74585d4f9ac7"),
                            Name = "Milk & dairy products",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 39
                        },
                        new
                        {
                            SectorId = new Guid("655c019d-44cc-4f00-98f0-dcd3235bbd4c"),
                            Name = "Other",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 437
                        },
                        new
                        {
                            SectorId = new Guid("870b9271-4366-45e0-bc87-83b660dafa3c"),
                            Name = "Sweets & snack food",
                            ParentId = new Guid("f9da9ee9-7ae0-4306-8474-97da9d2c0ec2"),
                            Value = 378
                        },
                        new
                        {
                            SectorId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Name = "Furniture",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 13
                        },
                        new
                        {
                            SectorId = new Guid("959ec62e-1a1f-47ab-8a95-0b294194e3bc"),
                            Name = "Bathroom/sauna",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 389
                        },
                        new
                        {
                            SectorId = new Guid("edd8138d-eff5-4354-9779-1ce853bbedea"),
                            Name = "Bedroom",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 385
                        },
                        new
                        {
                            SectorId = new Guid("0ee0b603-a50a-4c5f-9a97-a43dccc76d3d"),
                            Name = "Children's room",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 390
                        },
                        new
                        {
                            SectorId = new Guid("4ed77c1b-1c0c-44e7-8a92-98b5e6fb2401"),
                            Name = "Kitchen",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 98
                        },
                        new
                        {
                            SectorId = new Guid("bd5b3044-b2cf-4ede-8896-b7166513955b"),
                            Name = "Living room",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 101
                        },
                        new
                        {
                            SectorId = new Guid("46bda4d0-34ef-4db1-9fe3-72c5f0732a07"),
                            Name = "Office",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 392
                        },
                        new
                        {
                            SectorId = new Guid("933e89c9-699e-4325-ac2f-b2114c23fc7c"),
                            Name = "Other (Furniture)",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 394
                        },
                        new
                        {
                            SectorId = new Guid("73312d98-1b06-4463-be0e-573ffb85105c"),
                            Name = "Outdoor",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 341
                        },
                        new
                        {
                            SectorId = new Guid("2d6e3a8d-a80e-4bd7-ac99-afd32d9f7943"),
                            Name = "Project furniture",
                            ParentId = new Guid("076c44f7-e704-4717-8d94-665ac1db0918"),
                            Value = 99
                        },
                        new
                        {
                            SectorId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Name = "Machinery",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 12
                        },
                        new
                        {
                            SectorId = new Guid("7a892afc-5ffc-49c0-90d4-e20770b0055d"),
                            Name = "Machinery components",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 94
                        },
                        new
                        {
                            SectorId = new Guid("61068c29-1071-4084-b728-bfe5c8e0a554"),
                            Name = "Machinery equipment/tools",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 91
                        },
                        new
                        {
                            SectorId = new Guid("47b83906-2d2a-4849-882e-cfc520f6bf51"),
                            Name = "Manufacture of machinery",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 224
                        },
                        new
                        {
                            SectorId = new Guid("8c8e9331-f5b3-4560-961d-3f2351dd953f"),
                            Name = "Maritime",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 97
                        },
                        new
                        {
                            SectorId = new Guid("72ee0625-bb8f-4a5e-b707-a1cba55e2702"),
                            Name = "Aluminium and steel workboats",
                            ParentId = new Guid("8c8e9331-f5b3-4560-961d-3f2351dd953f"),
                            Value = 271
                        },
                        new
                        {
                            SectorId = new Guid("51ebfd2d-70c4-4e3d-a220-891268345456"),
                            Name = "Boat/Yacht building",
                            ParentId = new Guid("8c8e9331-f5b3-4560-961d-3f2351dd953f"),
                            Value = 269
                        },
                        new
                        {
                            SectorId = new Guid("c75d45f7-68b1-4537-9ad4-fd8c6168dbbf"),
                            Name = "Ship repair and conversion",
                            ParentId = new Guid("8c8e9331-f5b3-4560-961d-3f2351dd953f"),
                            Value = 230
                        },
                        new
                        {
                            SectorId = new Guid("d6ce4a6d-9fde-4179-908b-c088b14718f4"),
                            Name = "Metal structures",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 93
                        },
                        new
                        {
                            SectorId = new Guid("6fac4877-ec2a-4539-b553-703e618bfdb9"),
                            Name = "Other",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 508
                        },
                        new
                        {
                            SectorId = new Guid("95064bcb-8e39-4b51-be1c-9f4f575fbc9f"),
                            Name = "Repair and maintenance service",
                            ParentId = new Guid("0d2d5955-a5a8-4f1c-a72c-6c905eea8904"),
                            Value = 227
                        },
                        new
                        {
                            SectorId = new Guid("f2a5bd1a-76c8-43e5-a57f-1c47db0a6db7"),
                            Name = "Metalworking",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 11
                        },
                        new
                        {
                            SectorId = new Guid("4b579f27-8d09-411b-88e4-c30447f703c4"),
                            Name = "Construction of metal structures",
                            ParentId = new Guid("f2a5bd1a-76c8-43e5-a57f-1c47db0a6db7"),
                            Value = 67
                        },
                        new
                        {
                            SectorId = new Guid("5f248e37-7697-42d6-9cbb-f2694b3c3cfb"),
                            Name = "Houses and buildings",
                            ParentId = new Guid("f2a5bd1a-76c8-43e5-a57f-1c47db0a6db7"),
                            Value = 263
                        },
                        new
                        {
                            SectorId = new Guid("3f2e067a-9593-46d4-8318-a6925da13dfa"),
                            Name = "Metal products",
                            ParentId = new Guid("f2a5bd1a-76c8-43e5-a57f-1c47db0a6db7"),
                            Value = 267
                        },
                        new
                        {
                            SectorId = new Guid("f0d77910-bd74-452e-8716-c347be4148e6"),
                            Name = "Metal works",
                            ParentId = new Guid("f2a5bd1a-76c8-43e5-a57f-1c47db0a6db7"),
                            Value = 542
                        },
                        new
                        {
                            SectorId = new Guid("f8618be7-03c5-44b3-8904-95b01d09c548"),
                            Name = "CNC-machining",
                            ParentId = new Guid("f0d77910-bd74-452e-8716-c347be4148e6"),
                            Value = 75
                        },
                        new
                        {
                            SectorId = new Guid("6a9faa0b-2c67-40a8-8251-e219a3304f7e"),
                            Name = "Forgings, Fasteners",
                            ParentId = new Guid("f0d77910-bd74-452e-8716-c347be4148e6"),
                            Value = 62
                        },
                        new
                        {
                            SectorId = new Guid("102d0053-9220-4496-9470-7e854ee45b27"),
                            Name = "Gas, Plasma, Laser cutting",
                            ParentId = new Guid("f0d77910-bd74-452e-8716-c347be4148e6"),
                            Value = 69
                        },
                        new
                        {
                            SectorId = new Guid("8069fdc9-1573-45b0-91f6-7f7b3539fc7d"),
                            Name = "MIG, TIG, Aluminum welding",
                            ParentId = new Guid("f0d77910-bd74-452e-8716-c347be4148e6"),
                            Value = 66
                        },
                        new
                        {
                            SectorId = new Guid("ca207960-b32e-4c98-aabb-37b5468bf9f9"),
                            Name = "Plastic and Rubber",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 9
                        },
                        new
                        {
                            SectorId = new Guid("4ddeb2e1-0c8a-4c79-8a21-744a44708b95"),
                            Name = "Packaging",
                            ParentId = new Guid("ca207960-b32e-4c98-aabb-37b5468bf9f9"),
                            Value = 54
                        },
                        new
                        {
                            SectorId = new Guid("25ccaa72-4e7d-4b1a-83d8-b50a92d52353"),
                            Name = "Plastic goods",
                            ParentId = new Guid("ca207960-b32e-4c98-aabb-37b5468bf9f9"),
                            Value = 556
                        },
                        new
                        {
                            SectorId = new Guid("ddc7296c-2aa3-482a-8dec-422b87588a9d"),
                            Name = "Plastic processing technology",
                            ParentId = new Guid("ca207960-b32e-4c98-aabb-37b5468bf9f9"),
                            Value = 559
                        },
                        new
                        {
                            SectorId = new Guid("f8113241-85fe-4c21-8c40-e5f42b52a87f"),
                            Name = "Blowing",
                            ParentId = new Guid("ddc7296c-2aa3-482a-8dec-422b87588a9d"),
                            Value = 55
                        },
                        new
                        {
                            SectorId = new Guid("71e9659f-2c0c-4ac8-90cd-626969a14d65"),
                            Name = "Moulding",
                            ParentId = new Guid("ddc7296c-2aa3-482a-8dec-422b87588a9d"),
                            Value = 57
                        },
                        new
                        {
                            SectorId = new Guid("1a731b02-69d9-42be-82a9-70bef359bb92"),
                            Name = "Plastics welding and processing",
                            ParentId = new Guid("ddc7296c-2aa3-482a-8dec-422b87588a9d"),
                            Value = 53
                        },
                        new
                        {
                            SectorId = new Guid("0ad93be5-a92e-4254-9531-2c6b10eb5687"),
                            Name = "Plastic profiles",
                            ParentId = new Guid("ca207960-b32e-4c98-aabb-37b5468bf9f9"),
                            Value = 560
                        },
                        new
                        {
                            SectorId = new Guid("a56c4a64-78e5-4e5c-8a34-a306164ca7c5"),
                            Name = "Printing",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 5
                        },
                        new
                        {
                            SectorId = new Guid("d9330a46-75a8-4317-80b1-9ab8442a9b6d"),
                            Name = "Advertising",
                            ParentId = new Guid("a56c4a64-78e5-4e5c-8a34-a306164ca7c5"),
                            Value = 148
                        },
                        new
                        {
                            SectorId = new Guid("6fe3d7bd-e246-4fc9-903a-4a6170922663"),
                            Name = "Book/Periodicals printing",
                            ParentId = new Guid("a56c4a64-78e5-4e5c-8a34-a306164ca7c5"),
                            Value = 150
                        },
                        new
                        {
                            SectorId = new Guid("eb8f9b38-6b69-4b1d-84f0-1ae8d25cfd04"),
                            Name = "Labelling and packaging printing",
                            ParentId = new Guid("a56c4a64-78e5-4e5c-8a34-a306164ca7c5"),
                            Value = 145
                        },
                        new
                        {
                            SectorId = new Guid("0c911af0-24b1-43dd-b01e-8b292effd4aa"),
                            Name = "Textile and Clothing",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 7
                        },
                        new
                        {
                            SectorId = new Guid("65a70974-805b-4596-9f78-e605fe762fc9"),
                            Name = "Clothing",
                            ParentId = new Guid("0c911af0-24b1-43dd-b01e-8b292effd4aa"),
                            Value = 44
                        },
                        new
                        {
                            SectorId = new Guid("269c431d-96ce-4752-9690-e981490bf91f"),
                            Name = "Textile",
                            ParentId = new Guid("0c911af0-24b1-43dd-b01e-8b292effd4aa"),
                            Value = 45
                        },
                        new
                        {
                            SectorId = new Guid("64a3df01-5638-4858-8351-656eec0415a9"),
                            Name = "Wood",
                            ParentId = new Guid("62528f0d-0e87-4b3b-b1ef-e5106ee79bcd"),
                            Value = 8
                        },
                        new
                        {
                            SectorId = new Guid("7d1eb2c9-a1a7-46b4-b112-a2b751192d36"),
                            Name = "Other (Wood)",
                            ParentId = new Guid("64a3df01-5638-4858-8351-656eec0415a9"),
                            Value = 337
                        },
                        new
                        {
                            SectorId = new Guid("d53584c2-4e67-42b3-8f67-5a308973b20b"),
                            Name = "Wooden building materials",
                            ParentId = new Guid("64a3df01-5638-4858-8351-656eec0415a9"),
                            Value = 51
                        },
                        new
                        {
                            SectorId = new Guid("2ca4e032-fc43-445b-89ea-c7ca116360af"),
                            Name = "Wooden houses",
                            ParentId = new Guid("64a3df01-5638-4858-8351-656eec0415a9"),
                            Value = 47
                        },
                        new
                        {
                            SectorId = new Guid("b7d1b767-757f-4a17-a83f-3a8054b8678c"),
                            Name = "Other",
                            Value = 3
                        },
                        new
                        {
                            SectorId = new Guid("35ff055c-7cff-4992-a1d9-a7c050da86b6"),
                            Name = "Creative industries",
                            ParentId = new Guid("b7d1b767-757f-4a17-a83f-3a8054b8678c"),
                            Value = 37
                        },
                        new
                        {
                            SectorId = new Guid("209e774a-910e-455f-b50d-42f283567b0c"),
                            Name = "Energy technology",
                            ParentId = new Guid("b7d1b767-757f-4a17-a83f-3a8054b8678c"),
                            Value = 29
                        },
                        new
                        {
                            SectorId = new Guid("ab858701-8f9d-4210-b56f-37a9076f0336"),
                            Name = "Environment",
                            ParentId = new Guid("b7d1b767-757f-4a17-a83f-3a8054b8678c"),
                            Value = 33
                        },
                        new
                        {
                            SectorId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Name = "Service",
                            Value = 2
                        },
                        new
                        {
                            SectorId = new Guid("ac250e4c-f5d6-4e8f-8a1b-810e24883d1d"),
                            Name = "Business services",
                            ParentId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Value = 25
                        },
                        new
                        {
                            SectorId = new Guid("45c160c7-143f-4a30-8a6d-e168d41222b1"),
                            Name = "Engineering",
                            ParentId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Value = 35
                        },
                        new
                        {
                            SectorId = new Guid("d7cfc0b9-7a0c-4aa6-99b3-7d3c65ae3915"),
                            Name = "Information Technology and Telecommunications",
                            ParentId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Value = 28
                        },
                        new
                        {
                            SectorId = new Guid("425891a2-8522-49ed-93f8-4826f4ab69e2"),
                            Name = "Data processing, Web portals, E-marketing",
                            ParentId = new Guid("d7cfc0b9-7a0c-4aa6-99b3-7d3c65ae3915"),
                            Value = 581
                        },
                        new
                        {
                            SectorId = new Guid("bfa1d68c-d82e-46ad-a966-9bae9833af04"),
                            Name = "Programming, Consultancy",
                            ParentId = new Guid("d7cfc0b9-7a0c-4aa6-99b3-7d3c65ae3915"),
                            Value = 576
                        },
                        new
                        {
                            SectorId = new Guid("ddeff8eb-cb5e-4ff5-860f-d4046663f45b"),
                            Name = "Software, Hardware",
                            ParentId = new Guid("d7cfc0b9-7a0c-4aa6-99b3-7d3c65ae3915"),
                            Value = 121
                        },
                        new
                        {
                            SectorId = new Guid("b22949f7-107f-42ba-8fcc-0cf10922b8e9"),
                            Name = "Telecommunications",
                            ParentId = new Guid("d7cfc0b9-7a0c-4aa6-99b3-7d3c65ae3915"),
                            Value = 122
                        },
                        new
                        {
                            SectorId = new Guid("87ac49c4-a1aa-4414-83a0-3f3cb9326812"),
                            Name = "Tourism",
                            ParentId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Value = 22
                        },
                        new
                        {
                            SectorId = new Guid("9617fc1a-f498-4eb8-86ce-3f23c7507c42"),
                            Name = "Translation services",
                            ParentId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Value = 141
                        },
                        new
                        {
                            SectorId = new Guid("cd5933ec-2dc9-4155-8fc1-3e3944d1e614"),
                            Name = "Transport and Logistics",
                            ParentId = new Guid("694920d3-c406-4645-8cea-4ae3196d0d87"),
                            Value = 21
                        },
                        new
                        {
                            SectorId = new Guid("4ff334c8-633c-4b1c-8e83-613c9812e38a"),
                            Name = "Air",
                            ParentId = new Guid("cd5933ec-2dc9-4155-8fc1-3e3944d1e614"),
                            Value = 111
                        },
                        new
                        {
                            SectorId = new Guid("247f282a-8589-4f4b-a500-0e5ebe450e90"),
                            Name = "Rail",
                            ParentId = new Guid("cd5933ec-2dc9-4155-8fc1-3e3944d1e614"),
                            Value = 114
                        },
                        new
                        {
                            SectorId = new Guid("3161267b-3534-43d0-802b-a8a653084ef1"),
                            Name = "Road",
                            ParentId = new Guid("cd5933ec-2dc9-4155-8fc1-3e3944d1e614"),
                            Value = 112
                        },
                        new
                        {
                            SectorId = new Guid("605a6420-140f-4b42-84d1-c4558fca1c85"),
                            Name = "Water",
                            ParentId = new Guid("cd5933ec-2dc9-4155-8fc1-3e3944d1e614"),
                            Value = 113
                        });
                });

            modelBuilder.Entity("BlueBird.Models.UserFormFilling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAgreedToTerms")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserFormFilling");
                });

            modelBuilder.Entity("BlueBird.Models.Sector", b =>
                {
                    b.HasOne("BlueBird.Models.UserFormFilling", "UserFormFilling")
                        .WithMany("Sectors")
                        .HasForeignKey("UserFormFillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFormFilling");
                });

            modelBuilder.Entity("BlueBird.Models.SectorData", b =>
                {
                    b.HasOne("BlueBird.Models.SectorData", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BlueBird.Models.SectorData", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BlueBird.Models.UserFormFilling", b =>
                {
                    b.Navigation("Sectors");
                });
#pragma warning restore 612, 618
        }
    }
}
